[package]
authors = ["Your Name <your.email@example.com>"]
edition = "2018"
name = "create_chat_gpt_input"
version = "0.1.0"

[dependencies]
clap = {version = "3.1.0", features = ["derive"]}

[[bin]]
name = "create_chat_gpt_input"
path = "src/main.rs"
